travis:
  secure:
    BINSTAR_TOKEN: FTfeFKnCpy81KmFmnKDnn0h9esY9WhAdyYLjZDWZC4MKUI1LqpAcfHwXimEOn2AIy7FdQpL31rzrCHMllXGIQehJscr8wxDaeMfurY3GrTJayTwDHUZ38e6e9cykGfEmlH8tI9U0ugObaF8QjnXCUHfrZVutMBBe0q43piTOVcc1VmuKS59UGBvUD4psPSpH9m1Fy0FR6irxncKViF0lFRzM5i09qcPl6G4wYAs4GpIh8lShNhFwZKU/8rc6SGl5cM0GJvXcmOjN2KKQ8dD0W/cMYPHE/GdqH9oXSXEtwkzASKDWZ0i6cMQn76NF8HbWPN6Y07B8pKuhNxgP+2Q9tI+KXXWcO/m//RcXQGilcbft4SqpcIE2ujeWtJRDnhtDYLw7Fnfm7NZSMdKbBgnZL65mW1xBI4esU3yChFk+ScTXsa8Lp6sxGMDUFsEwlg2j1ZjD/rcex2RbO6/KS2jxF78A2p+yRaj69JfVaG6gxBikBnjaZ8QfIE8yFVu3JhzC840tUZHFHkqOSZR5nxwwIp9fez+EKDO5N6VRi83nkoMcGyro2bedXPhyaBD1jfApDZCgTDkdsEdPPFRMWAqH3J7amOnoS87c0vrdDyBS5qp28gQmcCcByKpLRJMPaMkZrx+igjEpYnVUXqJ9lucGK0SQzvw1BBhB3gqBCcz0lCw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
